[package]
authors = ["clitic <clitic21@gmail.com>"]
categories = ["command-line-utilities"]
description = "Download video streams served over HTTP from websites, DASH (.mpd) and HLS (.m3u8) playlists."
documentation = "https://docs.rs/vsd"
edition = "2021"
exclude = ["docs", "images"]
keywords = ["m3u8"]
license = "MIT OR Apache-2.0"
name = "vsd"
repository = "https://github.com/clitic/vsd/tree/main/vsd"
version = "0.3.4"
readme = "README.md"

[dependencies]
aes = "0.8"
anyhow = "1"
base64 = "0.22"
cbc = "0.1"
chrono = "0.4"
clap = { version = "4", features = ["derive", "wrap_help"] }
cookie = "0.18"
ctrlc = "3"
dash-mpd = { version = "0.16.5", default-features = false }
glob = "0.3"
headless_chrome = { version = "1.0.10", optional = true }
hex = "0.4"
kdam = { version = "0.6", features = ["rich"] }
m3u8-rs = "6.0.0"
mp4decrypt = { version = "0.5", path = "../mp4decrypt" }
rayon = "1"
regex = "1"
requestty = "0.5.0"
reqwest = { version = "0.12", default-features = false, features = ["blocking", "cookies", "socks"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
vsd-mp4 = { version = "0.1", path = "../vsd-mp4", features = ["pssh", "text-ttml", "text-vtt"] }

[features]
default = ["browser", "native-tls"]
browser = ["dep:headless_chrome"]
native-tls = ["reqwest/native-tls"]
rustls-tls-webpki-roots = ["reqwest/rustls-tls-webpki-roots"]
rustls-tls-native-roots = ["reqwest/rustls-tls-native-roots"]
