name: build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true
      - name: list
        run: rustup default
      - name: Upload windows build
        uses: actions/upload-artifact@v4
        with:
          name: "vsd-${{ env.SHA }}-debug-x86_64-pc-windows-msvc"
          path: target/debug/vsd.exe
