name: build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true
      - name: Install dependencies
        run: sudo apt install protobuf-compiler
      - name: Build vsd
        run: cargo build -p vsd
      - name: Upload linux build
        uses: actions/upload-artifact@v4
        with:
          name: "vsd-$(git rev-parse --short HEAD)-debug-x86_64-unknown-linux-gnu"
          path: target/debug/vsd

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true
      - name: Install dependencies
        run: |
          Invoke-WebRequest -Uri "https://github.com/protocolbuffers/protobuf/releases/download/v30.1/protoc-30.1-win64.zip" -OutFile "protoc.zip"
          Expand-Archive -Path "protoc.zip" -DestinationPath "C:\protoc"
          echo "C:\protoc\bin" | Out-File -Append -FilePath $env:GITHUB_PATH
      - name: Build vsd
        run: cargo build -p vsd
      - name: Upload windows build
        uses: actions/upload-artifact@v4
        with:
          name: "vsd-$(git rev-parse --short HEAD)-debug-x86_64-pc-windows-msvc"
          path: target/debug/vsd.exe
