name: build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true
      - name: Install dependencies
        run: sudo apt install protobuf-compiler
      - name: Build vsd
        run: cargo build -p vsd
      - name: Upload linux build
        uses: actions/upload-artifact@v4
        with:
          name: "vsd-$(git rev-parse --short HEAD)-debug-x86_64-unknown-linux-gnu"
          path: target/debug/vsd

  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            submodules: true
      - name: Install dependencies
        uses: arduino/setup-protoc@v3
      - name: Build vsd
        run: cargo build -p vsd
      - name: Upload windows build
        uses: actions/upload-artifact@v4
        with:
          name: "vsd-$(git rev-parse --short HEAD)-debug-x86_64-pc-windows-msvc"
          path: target/debug/vsd.exe
